import prisma from '../prisma'
import { fetchTenantDataForEngine } from '../revenue-engine/adapter'
import { runRevenueLeakDetection } from '../revenue-engine'
import { OpportunityStatus, Prisma } from '@prisma/client'

/**
 * Persists the dynamic intelligence generated by the Revenue Leak Engine into the database.
 * Preserves deterministic behavior: avoids duplicating insights for the same leak state.
 */
export async function syncTenantOpportunities(tenantId: string) {
  try {
    // 1. Fetch live canonical state
    const data = await fetchTenantDataForEngine(tenantId)
    
    // 2. Run pure detection engine
    const detectionResult = runRevenueLeakDetection(data)
    
    // 3. Fetch existing opportunities for this tenant to manage idempotency
    const existingOpps = await prisma.recoveryOpportunity.findMany({
      where: { tenantId }
    })

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const operations: Prisma.PrismaPromise<any>[] = []

    for (const opp of detectionResult.opportunities) {
      // Compute deterministic correlation key to prevent duplicates even across concurrent runs
      const correlationKey = opp.paymentId ? `${opp.type}_PAY_${opp.paymentId}`
        : opp.subscriptionId ? `${opp.type}_SUB_${opp.subscriptionId}`
        : opp.checkoutSessionId ? `${opp.type}_CHK_${opp.checkoutSessionId}`
        : `${opp.type}_CUST_${opp.customerId || 'global'}`

      const match = existingOpps.find(eo => 
        eo.correlationKey === correlationKey ||
        (
          eo.type === opp.type &&
          (
            (opp.paymentId && eo.paymentId === opp.paymentId) ||
            (opp.subscriptionId && eo.subscriptionId === opp.subscriptionId) ||
            (opp.checkoutSessionId && eo.checkoutSessionId === opp.checkoutSessionId)
          )
        )
      )

      const oppData = {
        tenantId,
        customerId: opp.customerId || null,
        orderId: opp.orderId || null,
        paymentId: opp.paymentId || null,
        subscriptionId: opp.subscriptionId || null,
        checkoutSessionId: opp.checkoutSessionId || null,
        type: opp.type,
        correlationKey,
        amountAtRiskMinor: opp.amountAtRiskMinor,
        recoverableAmountMinor: opp.estimatedRecoverableAmountMinor,
        priority: opp.priority,
        score: opp.score,
        confidenceScore: opp.confidenceScore,
        reason: opp.reason,
        evidence: opp.evidence as Prisma.InputJsonValue,
        recommendation: opp.recommendation as Prisma.InputJsonValue | Prisma.NullableJsonNullValueInput,
      }

      if (match) {
        // Only update if it is still DETECTED. 
        // If an operator or system has resolved/dismissed/actioned it, preserve the operator lifecycle state.
        if (match.status === OpportunityStatus.DETECTED) {
          operations.push(
            prisma.recoveryOpportunity.update({
              where: { id: match.id },
              data: oppData
            })
          )
        }
      } else {
        // Create new opportunity with unique correlationKey
        operations.push(
          prisma.recoveryOpportunity.create({
            data: {
              ...oppData,
              status: OpportunityStatus.DETECTED,
              detectedAt: opp.detectedAt
            }
          })
        )
      }
    }

    // Execute idempotently inside a transaction
    if (operations.length > 0) {
      await prisma.$transaction(operations)
    }
  } catch (error) {
    console.error('[PERSIST_INSIGHTS_ERROR]', error)
    // We intentionally swallow this error so that it does not crash the upstream webhook ingestion.
    // The webhook ingestion is canonical financial state; intelligence generation is a side-effect.
  }
}
